site_name: K3F_n_rt
site_url: https://ivanrobuschi-custom.github.io/K3F_n_rt/
site_author: Custom S.p.A.
theme:
  name: material
  logo: assets/icons/logo.png
  favicon: assets/icons/favicon.png
  language: it
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Tema scuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Tema chiaro

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - tags

copyright: Copyright Custom S.p.A 2026

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - fenced_code
  - toc:
      permalink: true
nav:
- Home: index.md
- MANUALE UTENTE K3-N RT:
  - Introduzione: manuale-utente-k3-n-rt/index.md
  - Descrizione del Dispositivo: manuale-utente-k3-n-rt/descrizione-del-dispositivo.md
  - Installazione e Funzionamento di Base: manuale-utente-k3-n-rt/installazione-e-funzionamento-di-base.md
  - Operazioni di Vendita e Pagamento: manuale-utente-k3-n-rt/operazioni-di-vendita-e-pagamento.md
  - Rapporti Statistici e Azzeramenti: manuale-utente-k3-n-rt/rapporti-statistici-e-azzeramenti.md
  - Servizi Telematici e Lotteria degli Scontrini: manuale-utente-k3-n-rt/servizi-telematici-e-lotteria-degli-scontrini.md
  - Programmazione e Configurazione Avanzata: manuale-utente-k3-n-rt/programmazione-e-configurazione-avanzata.md
  - Manutenzione e Specifiche Tecniche: manuale-utente-k3-n-rt/manutenzione-e-specifiche-tecniche.md
